config/routes.rb
Rails.application.routes.draw do

  root to: "static#home"
  get "/problem", to: "static#problem", as: "missing_credentials"

  resources :customers
  resources :appointments
  resources :employees do
    resources :appointments, only: [:new, :create, :index]
  end

  get "/signup", to: "users#new", as: "signup"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"

  delete "/logout", to: "sessions#destroy", as: "destroy_user_session"

  get "/employee_login", to: "sessions#new_employee", as: "employee_login"
  post "/employee_login", to: "sessions#create_employee"

  get "/calendar", to: "simple_calendar#_month_calendar", as: "calendar"

  match '/auth/:google_oath2/callback' => "sessions#google", via: [:get, :post]

get "/ammount", to: "employees#ammount"

end

app/models/employee.rb
class Employee < ApplicationRecord

    has_many :appointments
    has_many :users, through: :appointments

    validates :username, presence: true, uniqueness: true
    validates :first_name, presence: true
    validates :last_name, presence: true
    has_secure_password
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

    before_action :find_employee, only: [:show, :edit, :destroy, :update]
    
    
    
    def index
        @employees = Employee.all 
    end

    def show 
    end
    
    def ammount
    
       @employees = Employee.all
    end

    private 
    
    def find_employee
        @employee = Employee.find_by_id(params[:id])
    end

    def employee_params
        params.require(:employee).permit(:username, :password, :first_name, :last_name, :bio, :picture)
    end
    


end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/ammount.html.erb
<h1>New</h1>

<% @employees.each do |e| %>
    <%= e.first_name %>
    <%= e.appointments.count%>
<%end%>

app/views/employees/index.html.erb
<div class= "container">
<br>
<br>
<br>
<h3 font-family: Georgia, serif; >&nbsp&nbsp&nbsp our stylists</h3>
<br>
<br>
<br>
<div class="row">
    <div class="col s4 m4">
<% @employees.each do |employee|%>
      <div class="card">
        <div class="card-image">
          <img src=<%= employee.picture %>>
          <span class="card-title"><%= employee.first_name %></span>
        </div>
        <div class="card-content">
          <p><%= employee.bio %></p>
        </div>
        <div class="card-action">
          <p class="text-black"><%= link_to "Schedule an appointment with " + employee.first_name , new_employee_appointment_path(employee) %></p>
        </div>
      </div>
<% end %>
    </div>
  </div>
</div>
    <br>
    <br>
    <br>
<%= render partial: "/layouts/footer" %>

app/views/employees/show.html.erb
<h1><%= @employee.first_name + " " + @employee.last_name %></h1>
<h3><%= @employee.bio %></h3>

<p><%= link_to "Schedule an appointment with #{@employee.first_name}", new_employee_appointment_path(@employee) %></p>

    <br>
    <br>
    <br>
<%= render partial: "/layouts/footer" %>