config/routes.rb
Rails.application.routes.draw do

  root to: "static#home"
  get "/problem", to: "static#problem", as: "missing_credentials"

  resources :customers
  resources :appointments
  resources :employees do
    resources :appointments, only: [:new, :create, :index]
  end

  get "/signup", to: "users#new", as: "signup"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"

  delete "/logout", to: "sessions#destroy", as: "destroy_user_session"

  get "/employee_login", to: "sessions#new_employee", as: "employee_login"
  post "/employee_login", to: "sessions#create_employee"

  get "/calendar", to: "simple_calendar#_month_calendar", as: "calendar"

  match '/auth/:google_oath2/callback' => "sessions#google", via: [:get, :post]

get "/ammount", to: "employees#ammount"

end

app/models/appointment.rb
class Appointment < ApplicationRecord

    validates_presence_of :name, :appointment_date
    belongs_to :employee
    belongs_to :user
    accepts_nested_attributes_for :employee
    accepts_nested_attributes_for :user

    def employee_first_name
        self.employee.first_name if self.employee
    end

    def start_time
        self.appointment_date ##Where 'start' is a attribute of type 'Date' accessible through MyModel's relationship
    end

    scope :past, -> { where('appointment_date <= ?', Time.current).order('appointment_date desc') }
    scope :current, -> { where('appointment_date >= ?', Time.current).order('appointment_date asc') }
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
    before_action :find_appointment, only: [:show, :edit, :destroy, :update]
    before_action :find_employee, only: [:new, :create, :show, :edit, :update]
    before_action :current_user, only: [:new, :create, :edit, :update, :show]
    before_action :current_employee, only: [:show, :edit, :update]
    before_action :redirect_if_not_logged_in, only: [:index, :show, :edit, :update]
    before_action :access?, only: [:show, :edit, :update]
    
    def index
        #@past_appointments = Appointment.past
        current_appointments
        past_appointments
        if !!current_employee
            @appointments = @employee.appointments 
        elsif !!current_user
            @appointments = @user.appointments
        else   
        end
    end

    def show
    end

    def new
        #byebug
        if !find_employee && !current_user  #not allowed to view the page
            redirect_to '/problem'
        elsif find_employee && !!current_user
            @appointment = @user.appointments.build
             render :new_employee_appointment
        elsif !!current_employee
            @appointment = @employee.appointments.build
            redirect_to root_path   
        else
            @appointment = Appointment.new
        end
    end

    def create 
        @appointment = @user.appointments.build(app_params)
        if @appointment.save
            #what to do if valid
            redirect_to appointments_path
        else 
            flash.now[:error] = @appointment.errors.full_messages
                render :new
        end
    end
 
    def edit
    end

    def update
        if @appointment.update(app_params)
            redirect_to appointment_path
        else
            flash.now[:error] = @appointment.errors.full_messages
            render :edit
        end
    end

    def destroy
        @appointment.destroy
        flash[:notice] = "Your appointment scheduled for #{@appointment.appointment_date} has been deleted."
        redirect_to appointments_path
    end

    def simple_calendar
    end

    private

        def find_appointment
            @appointment = Appointment.find_by_id(params[:id])
        end

        def past_appointments
            if current_user
                @past_appointments = current_user.appointments.past
            elsif current_employee
                @past_appointments = current_employee.appointments.past
            end
        end

        def current_appointments
            if current_user
                @current_appointments = Appointment.current.where(user_id: current_user.id)
            elsif   current_employee 
                @current_appointments = Appointment.current.where(employee_id: current_employee.id)
            end
        end

        def find_employee
            if params[:employee_id]
                @employee = Employee.find_by_id(params[:employee_id])
            end
        end

        def find_user
            if params[:user_id]
                @user = User.find_by_id(params[:user_id])
            end
        end

        def app_params
            params.require(:appointment).permit(:name, :appointment_date, :employee_id, :user_id)
        end

    
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_calendar.html.erb
<%= month_calendar(events: appointments) do |date, appointments| %>
    <%= date.day %>
    <%if  !appointments.nil? %>
      <% appointments.each do |appointment| %>
        <div>
          <%= link_to appointment.name, appointment_path(appointment) %>
        </div>
      <% end %>
    <% end %>
  <% end %>

app/views/appointments/_form.html.erb
<%= form_for appointment do |f| %>

        <%= f.collection_select :employee_id, Employee.all, :id, :first_name, prompt: true, class: "browser-default" %>
    <br>
    <br>
    <div>
        <%= f.label :appointment_date %>
        <%= f.datetime_field :appointment_date %>
    </div> 
    <br>
    <br>
    <div>   
        <%= f.label :name %>
        <%= f.text_field :name, placeholder: "Notes/Requests" %>
    </div>
    <br>
    <br>
    <br>
    <br>
   
    <%= f.submit button_name, :class => "btn grey darken-4 white-text right" %>

<% end %>

<script>$(document).ready(function(){
    $('select').formSelect();
  });</script>

  

app/views/appointments/edit.html.erb
<div class= "container" >
<br>
<br>
<br>
<h3> alter your appointment </h3>
<br>
<br>
<br>
<%= render partial: "form", locals: { appointment: @appointment, button_name: "Edit Appointment", } %>
</div>
    <br>
    <br>
    <br>
<%= render partial: "/layouts/footer" %>

app/views/appointments/index.html.erb
<div class= "container">
<br>
<br>
<br>
<h3>&nbsp&nbsp&nbsp your calendar</h3>
<br>
<br>
<br>
<%= render partial: "calendar", locals: {appointments: @appointments} %>

<h3>&nbsp&nbsp&nbsp upcoming</h3>

   <% @current_appointments.each do |appointment|%>
        <li><%= link_to appointment.employee.first_name, appointment_path(appointment) %></li>
        <ul>&nbsp&nbsp&nbspDate: <%= appointment.appointment_date.strftime("%m / %d") %></ul>
        <ul>&nbsp&nbsp&nbspTime: <%= appointment.appointment_date.strftime("%l : %M - %p") %></ul>
    <%end%>
<h3>&nbsp&nbsp&nbsp past</h3>
    <br>
    <% @past_appointments.each do |appointment|%>
        <li><%= link_to appointment.employee.first_name, appointment_path(appointment) %></li>
        <ul>&nbsp&nbsp&nbspDate: <%= appointment.appointment_date.strftime("%m / %d") %></ul>
        <ul>&nbsp&nbsp&nbspTime: <%= appointment.appointment_date.strftime("%l : %M - %p") %></ul>
    <%end%>


</ul>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<%= render partial: "/layouts/footer" %>

app/views/appointments/new.html.erb
<div class= "container">
<br>
<br>
<br>
<h3>&nbsp&nbsp&nbsp plan your visit</h3>
<br>
<br>
<br>

<%= render partial: "form", locals: { appointment: @appointment, button_name: "Schedule Appointment" } %>

</div>
<br>
   
<%= render partial: "/layouts/footer" %>

app/views/appointments/new_employee_appointment.html.erb
<div class= "container">
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
img {
  border-radius: 50%;
}
</style>
</head>
<body>
<br>
<br>
<br>

<img src=<%= @employee.picture %> alt="Avatar" style="width:200px">

</body>
</html> 
<br>
<br>
<br>
<h3>schedule your appointment with <%= @employee.first_name %></h3>
<br>
<br>
<br>

<%= form_for [@employee, @appointment] do |f| %>
    <%= f.hidden_field :employee_id, value: @employee.id %>
    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div> 
    <br>
    <br>
    <br>
    <div>   
        <%= f.label :appointment_date %>
        <%= f.datetime_field :appointment_date %>
    </div>
    <br>
    <br>
    <br>

    

    <%= f.submit "schedule appointment", class: 'btn btn-large right grey darken-2' %>

<% end %>

</div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
<%= render partial: "/layouts/footer" %>

app/views/appointments/show.html.erb
<div class= "container">
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
img {
  border-radius: 50%;
}
</style>
</head>
<body>
<br>
<br>
<br>
<br>
<br>

<img src=<%= @appointment.employee.picture %> alt="Avatar" style="width:200px">

</body>
</html> 




<br>
<br>
<br>
<h3>You have an appointment scheduled with <%= @appointment.employee_first_name %></h3>
<br>
<h4>Date: <%= @appointment.appointment_date.strftime("%m / %d") %></h4>

<h4>Time: <%= @appointment.appointment_date.strftime("%l : %M - %p") %></h4>

<h4>Notes: <%= @appointment.name %></h4>

<%= link_to "Delete", appointment_path(@appointment), method: "delete", class: 'btn btn-large right black' %>
</div>
<%= link_to "Edit Appointment", edit_appointment_path(@appointment), class: 'btn btn-large right grey darken-2' %> 
    <br>
    <br>
    <br>
<%= render partial: "/layouts/footer" %>