config/routes.rb
Rails.application.routes.draw do

  root to: "static#home"
  get "/problem", to: "static#problem", as: "missing_credentials"

  resources :customers
  resources :appointments
  resources :employees do
    resources :appointments, only: [:new, :create, :index]
  end

  get "/signup", to: "users#new", as: "signup"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new", as: "login"
  post "/login", to: "sessions#create"

  delete "/logout", to: "sessions#destroy", as: "destroy_user_session"

  get "/employee_login", to: "sessions#new_employee", as: "employee_login"
  post "/employee_login", to: "sessions#create_employee"

  get "/calendar", to: "simple_calendar#_month_calendar", as: "calendar"

  match '/auth/:google_oath2/callback' => "sessions#google", via: [:get, :post]

get "/ammount", to: "employees#ammount"

end

app/views/layouts/_errors.html.erb
<% if flash[:error] %>
    <% flash[:error].each do |error| %>
        <p><%= error %></p>
    <% end %>
<% end %>

<%= content_tag("p", flash[:notice]) if flash[:notice] %>

app/views/layouts/_footer.html.erb
<footer class="page-footer grey darken-4">
  <div class="footer-copyright grey darken-4">
    <div class="container">
      © 2021 Fake Copyright
      <%= link_to "Style Salon Home", root_path, class: 'right' %>
    </div>
  </div>
</footer>

<script>
  body {
    display: flex;
    min-height: 100vh;
    flex-direction: column;
  }

  main {
    flex: 1 0 auto;
  }
</script>
</footer>
    

app/views/layouts/_nav.html.erb
<nav  style="background: linear-gradient(#212121, #424242);" >
  <div class="container">
    <%= link_to("Style Salon", root_path, class: "brand-logo") %>
      <ul class="right">
        <% if user_signed_in? %> 
            <li><%= link_to "appointmnets", appointments_path %></li>
            <li><%= link_to "schedule appointmnet", new_appointment_path %></li>
            <li><%= link_to "stylists", employees_path %></li>
            <li><%= link_to "signout", destroy_user_session_path, method: "DELETE" %></li>
        <% elsif employee_signed_in? %>   
          <li><%= link_to "appointmnets", appointments_path %></li>    
          <li><%= link_to "signout", destroy_user_session_path, method: "DELETE" %></li>
        <% else  %>          
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SalonRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

   
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
            
    
<style>
body, h1, h2, h3, h4, h5, h6  {
  font-family: Georgia, serif;
}
<body>
</style>

  </head>



  <body>
    <%= render 'layouts/nav' %>
    <%= render 'layouts/errors' %>
      <div>
        <%= yield %>
      </div>
  </body>
</html>